"""empty message

Revision ID: 6c05d4de1a4a
Revises: 
Create Date: 2021-05-26 17:18:14.898309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c05d4de1a4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('greek_name', sa.Text(), nullable=True),
    sa.Column('french_name', sa.Text(), nullable=True),
    sa.Column('encycleme', sa.Boolean(), nullable=True),
    sa.Column('mechane', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('accessory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('lang', sa.Enum('greek', 'french'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('french_text', sa.Text(), nullable=True),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('mouvements', sa.Text(), nullable=True),
    sa.Column('cite', sa.Text(), nullable=True),
    sa.Column('sentence_num', sa.Integer(), nullable=True),
    sa.Column('unit_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit')
    op.drop_table('character')
    op.drop_table('accessory')
    op.drop_table('project')
    # ### end Alembic commands ###
