"""empty message

Revision ID: f0515081db54
Revises: 8baa47b1e1ca
Create Date: 2021-05-14 16:39:32.484953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0515081db54'
down_revision = '8baa47b1e1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('unit_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'unit_num')
    # ### end Alembic commands ###
